spring:
    datasource:
      hikari:
        jdbc-url: jdbc:mysql://192.168.99.100:3306/testdb
        username: testuser
        password: passsword
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
    batch:
      job:
        enabled: false